---
title: "Sessions 5-6"
author: "T. Evgeniou"
date: "9 Jan 2016"
output: html_document
---
<br>

The purpose of this session is to become familiar with:

1. Understand the use of segmentation in practice;
2. Learn about classification and scoring methods;
3. See how these tools can be used in practice;
4. Introduce advanced methods for data analytics

As always, before starting, make sure you have pulled the [session 5-6 files](https://github.com/InseadDataAnalytics/INSEADAnalytics/tree/master/CourseSessions/Sessions45)  (yes, I know, it says sessions 4-5, but it is 5-6 - need to update all filenames some time, but till then we use common sense and ignore a bit the filenames) on your github repository (if you pull the course github repository you also get the session files automatically). Moreover, make sure you are in the directory of this exercise. Directory paths may be complicated, and sometimes a frustrating source of problems, so it is recommended that you use these R commands to find out your current working directory and, if needed, set it where you have the main files for the specific exercise/project (there are other ways, but for now just be aware of this path issue). For example, assuming we are now in the "MYDIRECTORY/INSEADAnalytics" directory, we can do these: 

```{r echo=TRUE, eval=FALSE, tidy=TRUE}
getwd()
setwd("CourseSessions/Sessions45")
list.files()
rm(list=ls()) # Clean up the memory, if we want to rerun from scratch
```
As always, you can use the `help` command in Rstudio to find out about any R function (e.g. type `help(list.files)` to learn what the R function `list.files` does).

Let's start.

<hr>
<hr>

### What are Classification and Scoring Methods for?

(work in progress)
