---
title : (Big) Data Analytics for Business
subtitle : Session 1, Introduction to Data Analytics for Business
author : T. Evgeniou and J. Niessing
job : INSEAD
widgets : []
mode : standalone 

---

## Today's Plan
  
  
  
Course Introduction

Example Applications

Data Analytics Processes

Introduction to the Tools

---

## Course Grading


  
  
Class Group Project (one):    40%

Group Assignment (one - in 3 parts):  	30%

Class Participation: 			30%

---

## What is Big Data? What is new? 


---

## Example Uses of Data Analytics

Marketing (i.e. acquisition, cross-sell, churn, etc)

Personalization (i.e. targeted advertisement)

Market positioning

Fraud detection

Monitoring of processes

Credit scoring and risk management

Financial modeling

Knowledge management and text mining

...

---


## Why this class? Three goals
  
  
  
1. <b style="color:#000;">Organizational Level:</b> Develop your intuition about identifying data analytics opportunities and their implementation challenges  
  
  
2. <b style="color:#000;">Project Level:</b> Learn how to approach data analytics projects  
  
  
3. <b style="color:#000;">Analysis Level:</b> Learn how to perform, read, and use key data analytics methods. 
  

---

## Is Data Analytics Disruptive for an Organization?
  
  
  
    
What <b style="color:#000;">changes</b> could it potentially imply for an organization?
  
  
For an industry?



---

## Project Level: The Data Analytics Project
  
  
  
  
Example: Detecting most likely customers to churn…
  
  
  
Goal: Minimize churn rate  
  
  
  
  <center>How would you proceed?</center>



---

## Data Analytics Processes


  
Step 1: Defining the Objective(s)  
  
  
Step 2: Data Preparation and Exploration
  
  
Step 3: Analysis
  
  
Step 4: Performance Assessment

---

## Step 2: Data Preparation and Exploration: Many Questions

What is available?

How much data is needed?

How much history is required?

What Data Quality issues do we have?

Which variables should be used?

What Derived Variables do we need?

What is the right level of granularity?

Is our Data Representative?

...

---

## Group Project: Deliverable #1

Please prepare a short report  as well as  a slidify presentation. You will need to post them on your  <b style="color:#000;">servers before the day of sessions 4-5</b>. Delayed reports will lose 20% of the group project grade. 

Provide 

- summary statistics of the data, 

- any initial visual/graphic summaries  

- an initial analysis based on sessions 2-3


---

## Group Project: Final Deliverable 
  
By Session 8 you need to have your final draft of the report and slides for your project.   
  
  
<b style="color:#000;">Your report and slides need to be public on your servers before session 8. </b> 

---

## Some Data Analytics Tools Covered

1. Finding important factors that summarize your data, and visualizing your data: 
<b style="color:#000;">Factor Analysis and Perceptual Maps</b> (Sessions 2 and 3)
  
  
  
2. Finding a few clusters of similar data: 
<b style="color:#000;">Cluster Analysis</b> (Sessions 4 and 5) 
  
  
  
3. Discriminating among and predicting successes vs failures: 
<b style="color:#000;">Logistic Regression and Tree Analysis</b> (Sessions 6 and 7)


---

## Software Tools for the Course
  
  
 See course website for instructions and links to various resources
  
  
- <b style="color:#000;">Great visualization examples</b>


- <b style="color:#000;">Github for collaboration</b>
  
  
- <b style="color:#000;">R and Rstudio</b>
  
  
- <b style="color:#000;">Knitr and creating nice reports</b>
  
  
- <b style="color:#000;">Slidify</b>
  
  
- <b style="color:#000;">Customized Data Analytics Web Application Tools</b>


---

## To Do Before Next Class (in groups if needed)

1. Explore the course website 

2. Explore RunStudy.R in the directory of Sessions 23 on your server 
    
3. Read the Boats case as well as the documents in your Data_Analytics_Case_MarketSegmentation_LuxuryGoods RStudio project or the <a href="http://inseaddataanalytics.github.io/INSEADjan2014/ProjectsMenu.html" target="_blank">projects website </a>

4. Become familiar with the technical instructions on the course website. 

5. Do NOT push anything on github yet!!! 
